name: Rector

on: [ push, pull_request ]

jobs:
    rector:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.3', '7.4', '8.0' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.11.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast, intl

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer's dependencies
                uses: actions/cache@v2.1.4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-composer-dependencies-cache

            -   name: Install Composer deps
                run: |
                    composer update --no-interaction --no-scripts
                    composer bin phpunit update

            -   name: Run Rector
                run: |
                    ./vendor/bin/rector process --dry-run
